# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Haunt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Haunt

  pod 'Firebase/Core' # firebase
  pod 'Firebase/Firestore' # firestore
  pod 'Firebase/Auth' #Auth
  pod 'Firebase/Storage' #firestorage
  pod 'FirebaseUI' #firebaseUI
  pod 'Kingfisher' # catch optimaization
  pod 'TabPageViewController' # infinity scroll

  target 'HauntTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HauntUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
